### ISSUE TITLE
Enviornment/UI/UX

### ISSUE THREAD

**Issue by CookiedOutMonster** [CookiedOutMonster/COSC441#4]
- Environment where the user should be standing 
- **Assets** for the **blocks** (logic to come? Communicate with Zee) 
- UI/UX on how the user interfaces with VR
- Please remain communicative regarding this portion, this part I understand the least.

**Comment by juliapetrie** [comment]
IMPORTANT: the ui can be really temperamental, and adding a package or asset or any system changes can easily corrupt the entire project; before making any significant changes, you need to save the scene as a new scene. Not just save --> please make a backup and save to the scenes folder. At the moment, I am operating in scene/b3, but we should decide if, as a group, we want to continually build upon the highest backup number or stick to a version and use the backups in case of corruption. 

There were some setbacks for the game environment, but a simple setting may be ideal for a study environment regardless.

**Tested two interaction types for blocks**
1. Ray casting (probably ideal)
2. Grab (block calls directly to user's hand on controller grab, nice for getting the blocks that you want but less ideal for organizing the blocks. There are two blue cubes: one has grab, and one has ray (I'll remove grab most likely, but I wanted to test it)

Block asset colours are provided and named (colours mostly from Zee's mock-up)

**UI changes**
With the small environment, I think having the whole area as a workspace is nice; I scraped the idea of a table for now as it is confined but kept a workspace (square) on the floor to imply where the user should work as well as a circle overhead lighting to keep user central. Despite this, the user can move anywhere but spawns in the center.  

**Organization**

-  use folders for adding scripts and materials
-  sort any added UI or game objects into existing folders or new folders

**Toolbox/ Whiteboard / Welcome screen**
- it would be nice if we could use this style or similar for panels (obviously, we can make it more narrow, but the style is fitting)
- Tested some drop boxes in the toolbox
- Originally, a text area in the welcome panel allowed participants to enter PID, but conflict issues were mixing a keyboard with VR. We can try another asset or workarounds if this is something we want to go with otherwise we can set up the study in the Inspector through a serialized field for PID (which I think is also okay)
